### ISSUE TITLE
use case?

### ISSUE THREAD

**Issue by flutschfinger** [alpico/authentication-scheme#5]
Hey,
the spec looks promising. What are the use cases? 
The spec states `We therefore employ a public-key signature scheme, where the private key never leaves the device it was generated on`. Can a device be anything? Browser, mobile phone, a server?

I think some use cases (with some auth flow charts) would be awesome :)

All the best
flutschfinger

**Comment by vmmon** [comment]
The main use-case is the authentication of a REST service.  The client than runs on embedded devices, development machines, servers or smart phones.  It can run as a native application or inside the browser. I even implemented it once in an iOS app....
